name: Build C++ Executable

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet Packages
      run: nuget restore DuneVisualsLoader/DuneVisuals1.21.4/DuneVisualsLoader.slnx

    - name: Build Project
      run: |
        msbuild DuneVisualsLoader/DuneVisuals1.21.4/DuneVisualsLoader.slnx /p:Configuration=Release /p:Platform=x64

    - name: Upload Executable Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DuneVisualsLoader-Build
        path: |
          DuneVisualsLoader/DuneVisuals1.21.4/**/Release/*.exe
          DuneVisualsLoader/DuneVisuals1.21.4/**/x64/Release/*.exe